include: package:flutter_lints/flutter.yaml

analyzer:
  plugins: riverpod_lint

plugins:
  riverpod_lint: 3.1.0

linter:
  rules:
    file_names: false
    non_constant_identifier_names: false
    always_use_package_imports: true
    constant_identifier_names: false
    null_check_on_nullable_type_parameter: false
